### ISSUE TITLE
navrh obsahu skoleni

### ISSUE THREAD

**Issue by landam** [GISMentors/qgis-pokrocily#1]
Diskuze k obsahu skoleni...

**Comment by landam** [comment]
Jedna z kapitol by se mohla tykat **hydrologie**, viz (1). Domluva je takova, ze na tom bude pracovat Ludka (termin: druha polovina ledna).

(1) https://github.com/GISMentors/grass-gis-pokrocily/tree/hydrologie2/hydrologie

**Comment by landam** [comment]
dalsi tema: **georeferencovani**

**Comment by jeleniste** [comment]
Pajtn skripty
Grafickej modelář (blbuvzdornej způsob jak řetězit)
Geoalgorytmy (plus vlastní skripty)
Jak psát pluginy

**Comment by jachym** [comment]
**modeler**, celé téma **qgis-grass**, customizace - **vlastní akce při kliknutí na prvek**, vlastní formuláře..

**Comment by jeleniste** [comment]
Celý téma qgis, postgis a databáze
Pak z pluginů metasearch a wcs

**Comment by jeleniste** [comment]
šikovná je taky kontrola topologie
Pak se daj ukázat střívka z qgis projektu

**Comment by jeleniste** [comment]
S těma db věcma bysem vám pochopitelně helfnul. Nebo si to můžete vykuchat z mojich materiálů. Akorát bacha na row_number() over() co tam doporu4uju. To je blbě.

**Comment by kalab-oto** [comment]
**geoalgorytmy** od ruznych posyktovatelu (GRASS, SAGA ...) a **modeler**, slozitejsi **symbologie** (na zaklade vice atributu)

**Comment by lfurtkevicova** [comment]
ja som si už dávnejšie chcela vyskúšať regionálnu štatistiku a diagramy ... nakoniec som si to dnes dovolila aj spraviť, viď. [Diagramy](https://github.com/GISMentors/qgis-pokrocily/blob/master/ruzne/grafy.rst)

**Comment by landam** [comment]
vypada to moc pekne!

**Comment by kalab-oto** [comment]
mohla by se zařadit i tvorba **atlasu** a popř. popis analýzy **viewshed**, taky mě napadlo, že by ve školení měly být primárně praktické věci, které se dají využít ve více oborech, tudíž budou zajímavé pro všechny účastníky (georeferencování, geoalgorytmy a modeler atd.) potom až nějaké speciality, které nevyužijí všichni v kurzu (třeba ten viewshed, nebo nějaké speciální pluginy)

**Comment by lfurtkevicova** [comment]
pracujem na kapitolke [vytvorenie pluginu](https://github.com/GISMentors/qgis-pokrocily/blob/master/ruzne/novy-plugin.rst) ... hydrológiu [hydro SCS-CN](https://github.com/GISMentors/qgis-pokrocily/blob/master/hydrologie/scs-cn.rst) a [hydro USLE](https://github.com/GISMentors/qgis-pokrocily/blob/master/hydrologie/usle.rst) + [diagramy](https://github.com/GISMentors/qgis-pokrocily/blob/master/ruzne/grafy.rst) považujem z mojej strany za dokončené
